package id.syizuril.app.mastsee;

import java.util.ArrayList;

public class PopularTvShowsData {
    public static String[][] data = new String[][]{
            {"See No Evil: The Moors Murders","2006","60","The dramatisation of one of the most notorious killing sprees in British history.","Christopher Menaul\nNicola Morrow","Ended","90m","Drama","https://image.tmdb.org/t/p/w600_and_h900_bestv2/b71BaRjp9TwxUZodLGgSRIlkfL8.jpg","https://image.tmdb.org/t/p/w533_and_h300_bestv2/7AKhSfJHnVi0zXQS4eJirHDs22p.jpg","https://image.tmdb.org/t/p/w533_and_h300_bestv2/7AKhSfJHnVi0zXQS4eJirHDs22p.jpg"},
            {"Stranger Things","2016","83","When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.","Ross Duffer\nMatt Duffer","Returning Series","50m","Drama, Mystery, SCI-FI & Fantasy","https://image.tmdb.org/t/p/w600_and_h900_bestv2/x2LSRK2Cm7MZhjluni1msVJ3wDF.jpg","https://image.tmdb.org/t/p/w533_and_h300_bestv2/56v2KjBlU4XaOv9rVYEQypROD7P.jpg","https://image.tmdb.org/t/p/w533_and_h300_bestv2/56v2KjBlU4XaOv9rVYEQypROD7P.jpg"},
            {"The Flash","2014","67","After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only \"meta-human\" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won't be long before the world learns what Barry Allen has become...The Flash.","Geoff Johns\nAndrew Kreisberg\nGreg Berlanti","Returning Series","44m","Drama, SCI-FI & Fantasy","https://image.tmdb.org/t/p/w600_and_h900_bestv2/fki3kBlwJzFp8QohL43g9ReV455.jpg","https://image.tmdb.org/t/p/w533_and_h300_bestv2/jC1KqsFx8ZyqJyQa2Ohi7xgL7XC.jpg","https://image.tmdb.org/t/p/w533_and_h300_bestv2/jC1KqsFx8ZyqJyQa2Ohi7xgL7XC.jpg"},
            {"One-Punch Man","2015","80","Saitama is a hero who only became a hero for fun. After three years of “special” training, though, he’s become so strong that he’s practically invincible. In fact, he’s too strong—even his mightiest opponents are taken out with a single punch, and it turns out that being devastatingly powerful is actually kind of a bore. With his passion for being a hero lost along with his hair, yet still faced with new enemies every day, how much longer can he keep it going?","Yuusuke Murata\nONE","Returning Series","24m","Action, Adventure, Animation, Comedy","https://image.tmdb.org/t/p/w600_and_h900_bestv2/iE3s0lG5QVdEHOEZnoAxjmMtvne.jpg","https://image.tmdb.org/t/p/w533_and_h300_bestv2/s0w8JbuNNxL1YgaHeDWih12C3jG.jpg","https://image.tmdb.org/t/p/w533_and_h300_bestv2/s0w8JbuNNxL1YgaHeDWih12C3jG.jpg"},
            {"Legion","2017","76","David Haller, AKA Legion, is a troubled young man who may be more than human. Diagnosed as schizophrenic, David has been in and out of psychiatric hospitals for years. But after a strange encounter with a fellow patient, he’s confronted with the possibility that the voices he hears and the visions he sees might be real.","Noah Hawley","Returning Series","50m","Action, Adventure, Sci-Fi, Fantasy","https://image.tmdb.org/t/p/w600_and_h900_bestv2/vT0Zsbm4GWd7llNjgWEtwY0CqOv.jpg","https://image.tmdb.org/t/p/w533_and_h300_bestv2/87eP7ITTrOWvkA4EqCuoRdyjzLy.jpg","https://image.tmdb.org/t/p/w533_and_h300_bestv2/87eP7ITTrOWvkA4EqCuoRdyjzLy.jpg"},
            {"Arrow","2012","58","Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea. He returns five years later a changed man, determined to clean up the city as a hooded vigilante armed with a bow.","Greg Berlanti\nMarc Guggenheim\nAndrew Kreisberg","Returning Series","42m","Action, Adventure, Drama, Crime, Mystery","https://image.tmdb.org/t/p/w600_and_h900_bestv2/mo0FP1GxOFZT4UDde7RFDz5APXF.jpg","https://image.tmdb.org/t/p/w533_and_h300_bestv2/dKxkwAJfGuznW8Hu0mhaDJtna0n.jpg","https://image.tmdb.org/t/p/w533_and_h300_bestv2/dKxkwAJfGuznW8Hu0mhaDJtna0n.jpg"},
            {"Grey's Anatomy","2005","63","Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.","Shonda Rhimes","Returning Series","43m","Drama","https://image.tmdb.org/t/p/w600_and_h900_bestv2/eqgIOObafPJitt8JNh1LuO2fvqu.jpg","https://image.tmdb.org/t/p/w533_and_h300_bestv2/y6JABtgWMVYPx84Rvy7tROU5aNH.jpg","https://image.tmdb.org/t/p/w533_and_h300_bestv2/y6JABtgWMVYPx84Rvy7tROU5aNH.jpg"},
            {"Dragon Ball","1986","71","Long ago in the mountains, a fighting master known as Gohan discovered a strange boy whom he named Goku. Gohan raised him and trained Goku in martial arts until he died. The young and very strong boy was on his own, but easily managed. Then one day, Goku met a teenage girl named Bulma, whose search for the dragon balls brought her to Goku's home. Together, they set off to find all seven dragon balls in an adventure that would change Goku's life forever. See how Goku met his life long friends Bulma, Yamcha, Krillin, Master Roshi and more.","Akira Toriyama","Ended","25m","Comedy, Sci-Fi, Fantasy, Animation, Action, Adventure","https://image.tmdb.org/t/p/w600_and_h900_bestv2/3wx3EAMtqnbSLhGG8NrqXriCUIQ.jpg","https://image.tmdb.org/t/p/w533_and_h300_bestv2/iflq7ZJfso6WC7gk9l1tD3unWK.jpg","https://image.tmdb.org/t/p/w533_and_h300_bestv2/iflq7ZJfso6WC7gk9l1tD3unWK.jpg"},
            {"The 100","2004","65","100 years in the future, when the Earth has been abandoned due to radioactivity, the last surviving humans live on an ark orbiting the planet — but the ark won't last forever. So the repressive regime picks 100 expendable juvenile delinquents to send down to Earth to see if the planet is still habitable.","Jason Rothenberg","Returning Series","43m","Drama, Sci-Fi, Fantasy","https://image.tmdb.org/t/p/w600_and_h900_bestv2/wBzNjurA8ijJPF21Ggs9nbviIzi.jpg","https://image.tmdb.org/t/p/w533_and_h300_bestv2/qYTIuJJ7fIehicAt3bl0vW70Sq6.jpg","https://image.tmdb.org/t/p/w533_and_h300_bestv2/qYTIuJJ7fIehicAt3bl0vW70Sq6.jpg"},
            {"DanMachi","2015","72","Bell Cranell is a rookie adventurer and the sole member of his dirt-poor guild founded by the petite goddess Hestia. Adventurers come from far and wide looking to strike it big in the massive labyrinth known as Dungeon, located beneath the city of Orario. Bell is more interested in picking up girls than Dungeon-crawling, but his reality check comes sooner than expected. Saved from a brush with death by the beautiful, renowned adventurer Aiz Wallenstein, Bell falls head-over-heels and sets his sights on winning her heart, but she's not the only woman he's caught the attention of, for better of worse.","Risa Taneda\nSaori Oonishi\nYoshitsugu Matsuoka","Returning Series","24m","Comedy, Sci-Fi, Fantasy, Animation","https://image.tmdb.org/t/p/w600_and_h900_bestv2/wuX4cucXdxad03jGWM0r3RQx1p6.jpg","https://image.tmdb.org/t/p/w533_and_h300_bestv2/ubnRfKVsQQukx8gk0ZCC4MlUxJA.jpg","https://image.tmdb.org/t/p/w533_and_h300_bestv2/ubnRfKVsQQukx8gk0ZCC4MlUxJA.jpg"},
    };

    static ArrayList<MoviesTVShows> getListData(){
        ArrayList<MoviesTVShows> popularList = new ArrayList<>();
        for (String[] aData: data){
            MoviesTVShows popularTVShows = new MoviesTVShows();
            popularTVShows.setTitle(aData[0]);
            popularTVShows.setDate(aData[1]);
            popularTVShows.setScore(aData[2]);
            popularTVShows.setOverview(aData[3]);
            popularTVShows.setCrew(aData[4]);
            popularTVShows.setStatus(aData[5]);
            popularTVShows.setRuntime(aData[6]);
            popularTVShows.setGenre(aData[7]);
            popularTVShows.setCover(aData[8]);
            popularTVShows.setBanner(aData[9]);
            popularTVShows.setAltbanner(aData[10]);

            popularList.add(popularTVShows);
        }
        return popularList;
    }
}
